# Generated by Django 4.2.2 on 2023-06-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDmot', models.IntegerField()),
                ('nomeMot', models.CharField(max_length=235)),
                ('nomeDoCarro', models.CharField(max_length=235)),
                ('placaDoCarro', models.CharField(max_length=235)),
                ('classificacaoEstrelas', models.IntegerField()),
                ('CPF', models.CharField(max_length=235)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
