# Generated by Django 4.2.2 on 2023-06-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itacar_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCorrida', models.IntegerField()),
                ('nomePass', models.CharField(max_length=255)),
                ('nota', models.IntegerField()),
                ('comentario', models.TextField()),
            ],
        ),
    ]
