# Generated by Django 4.2.2 on 2023-06-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itacar_app', '0003_historicoviagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioMotorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('IDmot', models.IntegerField()),
                ('nomeMot', models.CharField(max_length=235)),
                ('nomeDoCarro', models.CharField(max_length=235)),
                ('placaDoCarro', models.CharField(max_length=235)),
                ('classificacaoEstrelas', models.IntegerField()),
                ('CPF', models.CharField(max_length=235)),
            ],
        ),
        migrations.DeleteModel(
            name='Motorista',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
