# Generated by Django 4.2.2 on 2023-06-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itacar_app', '0004_usuariomotorista_delete_motorista_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariomotorista',
            name='IDmot',
        ),
        migrations.RemoveField(
            model_name='usuariomotorista',
            name='classificacaoEstrelas',
        ),
    ]
