# Generated by Django 4.2.2 on 2023-06-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itacar_app', '0005_remove_usuariomotorista_idmot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariomotorista',
            name='classificacaoEstrelas',
            field=models.IntegerField(default=0),
        ),
    ]
