# Generated by Django 4.2.2 on 2023-06-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itacar_app', '0006_usuariomotorista_classificacaoestrelas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePass', models.CharField(max_length=235)),
                ('CPF', models.CharField(max_length=235)),
                ('telefone', models.CharField(max_length=235)),
            ],
        ),
    ]
