# Generated by Django 4.2.2 on 2023-07-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itacar_app', '0007_passageiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('id_passageiro', models.TextField()),
                ('id_motorista', models.TextField()),
                ('id_viagem', models.IntegerField()),
                ('valor_recebido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxa_do_app', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gasto_medio_gasolina', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
