# Generated by Django 4.2.2 on 2023-07-03 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itacar_app', '0008_relatoriofinanceiro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatoriofinanceiro',
            old_name='valor_recebido',
            new_name='valor_recebido_total',
        ),
        migrations.RemoveField(
            model_name='relatoriofinanceiro',
            name='id_motorista',
        ),
        migrations.RemoveField(
            model_name='relatoriofinanceiro',
            name='id_passageiro',
        ),
        migrations.RemoveField(
            model_name='relatoriofinanceiro',
            name='id_viagem',
        ),
    ]
