# Generated by Django 4.2.2 on 2023-07-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itacar_app', '0009_rename_valor_recebido_relatoriofinanceiro_valor_recebido_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nomePass', models.CharField(max_length=235)),
                ('nomeMot', models.CharField(max_length=235)),
            ],
        ),
    ]
